//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCodeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCodeMaster()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CouponICoded { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> CouponType { get; set; }
        public Nullable<int> FlatAmount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> UsageLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
