//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCountry
    {
        public SCountry()
        {
            this.SCities = new HashSet<SCity>();
            this.SStates = new HashSet<SState>();
            this.Students = new HashSet<Student>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<SCity> SCities { get; set; }
        public virtual ICollection<SState> SStates { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
