//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentRegistration.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SState
    {
        public SState()
        {
            this.SCities = new HashSet<SCity>();
            this.Students = new HashSet<Student>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<SCity> SCities { get; set; }
        public virtual SCountry SCountry { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
