//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_326.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubId { get; set; }
        public string SubjectName { get; set; }
    }
}
