//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentResultManagement.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetails
    {
        public int StdDetailId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    
        public virtual StudentMaster StudentMaster { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
